apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanager-deployment
spec:
  selector:
    matchLabels:
      app: bookmanager
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bookmanager
    spec:
      containers:
        - name: bookmanager
          image: 055976367092.dkr.ecr.us-east-2.amazonaws.com/calcualtor:latest
          ports:
            - containerPort: 8080
