name: Build and Deploy calculator app in EKS Cluster
on:
  workflow_dispatch:
#push:
#  branches:
#    - feature/eks-deploy
env:
  WORKSPACE: module6
  CLUSTER_NAME: mycluster
  REGION: ap-south-1
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up ECR access
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 363267848264.dkr.ecr.ap-south-1.amazonaws.com
      
      - name: Build and push
        uses: docker/build-push-action@v4
        
        with:
         context: ./${{ env.WORKSPACE }}/docker-multistage
         push: true
         file: ${{ env.WORKSPACE }}/docker-multistage/Dockerfile
         tags: 363267848264.dkr.ecr.ap-south-1.amazonaws.com/calculator:${{ github.sha }}

  deploy-eks:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get Pod details
        id: updatedeployment
        uses: ianbelcher/eks-kubectl-action@master
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          args: set image deployment/calculator-deployment calculator=363267848264.dkr.ecr.ap-south-1.amazonaws.com/calculator:${{ github.sha }}
      
